### ISSUE TITLE
Swagger page points to wrong location of swagger file

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/website#118]
The test and build swagger page, https://goharbor.io/docs/2.1.0/build-customize-contribute/configure-swagger/, points to the main harbor repo /docs folder as the location of the swagger.yml file. This has changes since the /docs folder was moved into this repo.

This should be updated to the new location of the swagger file and to include any information on the how this file is versioned. 

**Questions:**

* What is the location of the swagger file now?
* How is the swagger file versioned?

**Comment by a-mccarthy** [comment]
@xaleeks can you help with the questions above? thanks!

**Comment by a-mccarthy** [comment]
@xaleeks were you able to check into this?

**Comment by heww** [comment]
Can this section [View and Test the Harbor REST API via Swagger](https://goharbor.io/docs/2.1.0/build-customize-contribute/configure-swagger/)  be removed from the document?  Harbor includes the swagger explorer in the portal from v1.8.

There is a related issue https://github.com/goharbor/harbor/issues/13552 in the harbor repo.

cc @xaleeks
