### ISSUE TITLE
Can you open the edit button on harbor docs page?

### ISSUE THREAD

**Issue by sober-wang** [goharbor/website#137]
We want contributer some documentary in Harbor docs. But we are  only wait you update the Harbor docs page. 
I feel this is unfriendly and decrease Harbor community funcution.
You should learning the kubernetes docs page , next add a  button for edit the docs page in the Harbor docs page.

![图片](https://user-images.githubusercontent.com/35804630/98504623-72b58380-2292-11eb-9d6f-79057858966c.png)

**Comment by reasonerjt** [comment]
I'm not sure if K8S and goharbor.io use netify the same way.
But you can always write up a PR if you want to propose any change to the doc.

**Comment by sober-wang** [comment]
no , PR is so lower , and unfriendly for some people.

**Comment by a-mccarthy** [comment]
+1 to PRs always being welcome if you have a change you want to propose. 

We do already have a Page Source button on the docs pages on the harbor site:

![Screen Shot 2020-11-09 at 10 37 07 AM](https://user-images.githubusercontent.com/20771501/98562415-0cbc0280-2278-11eb-9b2d-d3b42564128d.png)
.

**Comment by a-mccarthy** [comment]
closing this, since we already have this functionality built into the site.
