### ISSUE TITLE
Create a new web publishing workflow

### ISSUE THREAD

**Issue by jonasrosland** [goharbor/website#14]
The current publishing workflow through GitHub pages leaves a lot to be desired. It can be rather unintuitive for newcomers, and relies on us maintaining two separate repositories (/blog and /goharbor.github.io) for every change, small or large.

I propose moving away from GitHub pages and instead use [Netlify](https://www.netlify.com), which would then come with the following benefits:

- No need to maintain 2 repositories, we would have one source repo and that's it.
- Continuous integration and deployment, where every PR would generate a publicly viewable site so we can verify correct functionality before merge.
- Hugo works great with Netlify, so it would be an easy change - [more details on implementation here](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/).

Netlify is being used by [many open source projects](https://www.netlify.com/open-source/), such as Kubernetes, Lodash, and Yarn.

Thoughts and feedback on this?

**Comment by lucperkins** [comment]
@jonasrosland I can get this taken care of. PR forthcoming.

**Comment by lucperkins** [comment]
@jonasrosland Could you possibly make me an admin on this repository? That will speed the process a great deal.

**Comment by lucperkins** [comment]
The DNS has now been migrated, so we’re all set here.
