### ISSUE TITLE
/data/redis should also be removed before performing a clean re-installation

### ISSUE THREAD

**Issue by YahuiAn** [goharbor/website#152]
see [Other Commands](https://github.com/goharbor/website/blob/712a3c4531b3297d5fc61a6fe4cdf97274a8e760/docs/install-config/reconfigure-manage-lifecycle.md#other-commands)

**Comment by a-mccarthy** [comment]
include `data/redis` in the Other Commands section for what to remove before performing a clean re-installation on the /install-config/reconfigure-manage-lifecycle.md page.
