### ISSUE TITLE
Tables on some pages are too wide, content gets cut off

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/website#162]
* https://goharbor.io/docs/edge/install-config/configure-yml-file/
* https://goharbor.io/docs/edge/install-config/configure-user-settings-cli/
* https://goharbor.io/docs/edge/build-customize-contribute/registry-landscape/

**Comment by a-mccarthy** [comment]
@jonasrosland are you working on this? can I assign it to you?

**Comment by jonasrosland** [comment]
Anyone who would like to take this on, feel free to do so :)

**Comment by PaarthAgarwal** [comment]
I'm working on this issue but I can't see the changes I make in my local repository reflected in the website running on the local server. I need help with this
