### ISSUE TITLE
found create-tag-retention-rules may have a word miss

### ISSUE THREAD

**Issue by wkjun** [goharbor/website#253]
https://github.com/goharbor/website/blob/release-2.3.0/docs/working-with-projects/working-with-images/create-tag-retention-rules.md

```
You configure a retention policy to retain the two latest tags that match `harbor-*`, so that `harbor-rc` and `harbor-latest` are retained
```

according to the  file content, the `harbor-rc`  may change to `harbor-nightly`

**Comment by a-mccarthy** [comment]
Good find, looks like we should update `harbor-rc` to be `harbor-nightly` to make the example make sense. Are you willing to fix this issue?

**Comment by Xander23432** [comment]
Is anyone working on this issue right now..??
If not then I can work on this particular issue.

**Comment by a-mccarthy** [comment]
go for it @Xander23432! thanks!
