### ISSUE TITLE
Page occlusion

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/website#262]
url: https://goharbor.io/docs/2.3.0/install-config/configure-yml-file/
![image](https://user-images.githubusercontent.com/30999793/139647571-7e5fda9d-d973-4eb3-b74d-e7c8f5ec1c4e.png)

**Comment by a-mccarthy** [comment]
We have this issue noted in https://github.com/goharbor/website/issues/162. closing this in favor of keeping the conversation happing in a single place
