### ISSUE TITLE
Enterprise Logo Wrong - Netease Cloud

### ISSUE THREAD

**Issue by Qquanwei** [goharbor/website#27]
![image](https://user-images.githubusercontent.com/9263655/65112956-df791900-da13-11e9-98eb-00296b622983.png)
This logo is Netease Cloud Music without Netease Cloud. 
Netease Cloud Music: main website: https://music.163.com/

**Comment by jonasrosland** [comment]
Hi @Qquanwei, what's the correct logo? The one you have posted here is the one that's on the site:
![image](https://user-images.githubusercontent.com/1690215/65155991-42f74c80-d9fc-11e9-9294-5925c7a7eb13.png)

**Comment by Qquanwei** [comment]
Netease Cloud main website is: https://www.163yun.com/
I think the correct logo is, BUT I'm not the official.

![https://www.163yun.com/res/logo3.png](https://www.163yun.com/res/logo3.png)

**Comment by jonasrosland** [comment]
Thank you for raising the issue @Qquanwei. @steven-zou can you verify the correct logo for us to use here?

**Comment by steven-zou** [comment]
![NetEase](https://drive.google.com/file/d/1sSfHyBl2PsbgcOWO9PQxfCqZes4QDMgm/view?usp=sharing)

**Comment by jonasrosland** [comment]
Hi @Qquanwei , this has been fixed on the new website, thank you for your help here.
