### ISSUE TITLE
Artwork  Broken Link 

### ISSUE THREAD

**Issue by AbdelouahabMbarki** [goharbor/website#275]
Hi the Link pointing to the Logos https://branding.cncf.io/projects/harbor is Broken

**Comment by a-mccarthy** [comment]
This link can be found in the [config.toml file](https://github.com/goharbor/website/blob/main/config.toml). We need to update `logo_repo = "https://branding.cncf.io/projects/harbor"` to  `logo_repo = "https://github.com/cncf/artwork/tree/master/projects/harbor"`

**Comment by RishiKumarRay** [comment]
@a-mccarthy Can i raise a PR to fix this?

**Comment by a-mccarthy** [comment]
sure thing @RishiKumarRay! thanks

**Comment by RishiKumarRay** [comment]
@a-mccarthy Please do the review #284
