### ISSUE TITLE
Update `master` branch to `main`

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/website#276]
In out continued efforts to make sure that we are using inclusive terminology, we should update our default branch from `master` to `main`. This has already been done on the main harbor code repo, https://github.com/goharbor/harbor

**Comment by a-mccarthy** [comment]
also need to update the load file here, https://github.com/goharbor/website/blob/master/load-docs.sh

**Comment by jonasrosland** [comment]
Done, closing
