### ISSUE TITLE
Update links that point to the Harbor repo to point to main

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/website#283]
In our continued efforts to use inclusive wording within the harbor project, we have renamed the default branch of several harbor repos to use `main` instead of `master`. With this change we need to make sure that our docs are updated to point to the correct branch for content that lives in harbor repos.

The follow is a list of pages that have links to a Harbor repo that point to the master branch. We need to update the links on these pages to point to the main branch. 

For example we need to update links to be from `https://github.com/goharbor/harbor/blob/master/CONTRIBUTING.md` to `https://github.com/goharbor/harbor/blob/main/CONTRIBUTING.md`.

- [ ] https://github.com/goharbor/website/blob/main/docs/build-customize-contribute/_index.md - 1 link to update
- [ ] https://github.com/goharbor/website/blob/main/docs/administration/vulnerability-scanning/_index.md - 1 link to update
- [ ] https://github.com/goharbor/website/blob/main/content/community.md - 1 link to update
- [ ] https://github.com/goharbor/website/blob/main/docs/_index.md - 1 link to update
- [ ] https://github.com/goharbor/website/blob/main/docs/administration/metrics/_index.md - 4 links to update
- [ ] https://github.com/goharbor/website/blob/main/docs/administration/vulnerability-scanning/_index.md - 1 link to update
- [ ] https://github.com/goharbor/website/blob/main/docs/build-customize-contribute/developer-guide-i18n.md - 2 links to update
- [ ] https://github.com/goharbor/website/blob/main/docs/build-customize-contribute/e2e-api-python-based-scripting-guide.md - 1 link to update

If you have time to make one or more of these updates, please open an PR!

**Comment by adi611** [comment]
Please assign me this issue.

**Comment by a-mccarthy** [comment]
@adi611 thank you for volunteering to help

**Comment by a-mccarthy** [comment]
fixed in https://github.com/goharbor/website/pull/285

**Comment by a-mccarthy** [comment]
thanks @adi611!
