### ISSUE TITLE
Update Robot account screenshots for changed column name

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/website#289]
In 2.5, a column name on the Robot account pages of the Harbor interface were updated from "Expires At" to "Expires In". The information in the column now shows how long until the the account token expires and is color coded to better highlight to users when tokens will expire.

Related to the PR https://github.com/goharbor/harbor/pull/16227 and issue https://github.com/goharbor/harbor/issues/8282.

To do:
- [x] Update screenshots on https://goharbor.io/docs/2.4.0/administration/robot-accounts/
- [x] Update screenshots on https://goharbor.io/docs/2.4.0/working-with-projects/project-configuration/create-robot-accounts/

**Comment by a-mccarthy** [comment]
@AllForNothing can you review this issue and let me know if there were any other changes that need to be updated here? thanks!

**Comment by AllForNothing** [comment]
@a-mccarthy  
Below screenshot is the final version (updated after the UI designer's review)
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/30999793/155261037-eff912ec-7f01-4f51-a3a4-7bf03da2e532.png">
if  expired, it shows expired  with an error icon,  
if left days >= 7days,  it shows a green icon
if  7days > left days > 0 , it shows an waining icon
So,   Your TODO list is all you need to do
