### ISSUE TITLE
Updates for robot account

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/website#297]
In addition to the changes for the "Expires at" column

In 2.5, there are some other updates:
1. The number of permissions for robots has been increased to 18
2. "Select all" and "Unselect all" buttons were added for robot permission batch operation
<img width="991" alt="image" src="https://user-images.githubusercontent.com/30999793/157162555-8ba02b3f-bc8e-48bc-9a11-5f52c795246e.png">
3. Able to view what you input when refreshing secret
<img width="783" alt="image" src="https://user-images.githubusercontent.com/30999793/157162808-18b499dd-4a2e-426e-a8bd-9fa617e439d0.png">

So we need to update the related content in the documentation:

Todos:
1. Update the permission list(for both system robots and  project robots)
<img width="664" alt="image" src="https://user-images.githubusercontent.com/30999793/157161074-17a555f8-4e0b-4885-aae9-b36f9ff7dd22.png">

2. Update the related screenshots(for both system robots and  project robots)
<img width="793" alt="image" src="https://user-images.githubusercontent.com/30999793/157161284-9e66887a-8b12-4c87-be63-93c2b2f14bb6.png">
<img width="664" alt="image" src="https://user-images.githubusercontent.com/30999793/157164542-0944870f-4591-4a27-9fad-e22f01161d6c.png">

And  here are some additional information for the robot permissions for your reference:

1. Each permission is independent except for the "Push" permission,  it must work with "Pull" permission, that is, when you select "Push Repository", you must also select "Pull Repository"
<img width="864" alt="image" src="https://user-images.githubusercontent.com/30999793/157164325-1fcbdb73-6e2e-4f02-b72f-4e17d09477c9.png">
2. Each permission consists of two parts, an action, and a resource

**Comment by AllForNothing** [comment]
@a-mccarthy After testing and discussion, we will add another permission to 19 and sort the permissions. I will mention a PR later, please update the doc after my PR is merged

**Comment by AllForNothing** [comment]
@a-mccarthy Please update the doc after this PR is merged, https://github.com/goharbor/harbor/pull/16487
And your Harbor will also be updated

**Comment by a-mccarthy** [comment]
@AllForNothing thanks for filing this issue. I'll work on updating the docs. Just wanted to confirm, https://github.com/goharbor/harbor/pull/16487 is planned to be in 2.5, right?

**Comment by AllForNothing** [comment]
@a-mccarthy Yes.  Now, this PR is merged and your Harbor is also updated. You can start to update the doc.

**Comment by a-mccarthy** [comment]
Thank you @AllForNothing for writing this up!

I just want to make sure i understand what each permission does. Im a little confused about the differences between List Artifact and Read Artifact, for example. Can you make sure the following is correct? (most of the permission names are self descriptive, but i want i'm not missing an opportunity to explain things further in the docs, if needed) 

* List Repository - NEW - view repository information
* Pull Repository - formerly Pull Artifact - pull artifact from repository
* Push Repository - formerly Push Artifact - push artifact to repository
* Delete Repository - NEW - Delete repository
* Read Artifact - NEW - ??
* List Artifact - NEW - List artifact
* Delete Artifact - NEW - delete artifact
* Create Artifact Label - create label from an artifact in the repository
* Delete Artifact Label - NEW - delete label
* Create Tag - Create a tag for an artifact in a repository
* Delete Tag - Delete a tag from an artifact in a repository
* List Tag - NEW - list all tags for an artifact
* Create Scan - start artifact scan of repository
* Stop Scan - NEW - stop artifact scan of repository
* Read Helm Chart - read helm chart
* Create Helm Chart Version -  creates a helm chart version
* Delete Helm Chart Version - delete a helm chart version
* Create Helm Chart label - NEW - create helm chart label
* Delete Helm Chart label - NEW - delete helm chart label

**Comment by a-mccarthy** [comment]
@AllForNothing I also created a PR https://github.com/goharbor/website/pull/300

**Comment by AllForNothing** [comment]
@a-mccarthy List Artifact means you can read the list of all artifacts in the repository, Read Artifact means you can read the detailed info of an artifact. 
Yes,  your understanding is correct for other items
