### ISSUE TITLE
Update docs to use deactivate instead of disable

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/website#303]
The Harbor interface has been updated to use more inclusive terminology in https://github.com/goharbor/harbor/issues/16248. We should update the docs to reflect the changes in the interface.

This will include updating wording through the docs and screenshots. 

https://github.com/goharbor/harbor/issues/16248 updated the word `disable` to `deactivate`. So this is the change that needs to be made.

Hopefully we can do this using find replace on the website content in an editor.

**Comment by a-mccarthy** [comment]
@AllForNothing thank you for updating the Harbor interface. What Harbor release will we see these changes in the interface?

**Comment by AllForNothing** [comment]
@a-mccarthy Yes, these changes are in 2.6

**Comment by eugeneivanov101** [comment]
@a-mccarthy I checked the "administration" folder in "website/docs" and found 4 files with "disable":

https://github.com/goharbor/website/blob/main/docs/administration/configure-authentication/db-auth.md (1)
https://github.com/goharbor/website/blob/main/docs/administration/managing-users/user-permissions-by-role.md (3)
https://github.com/goharbor/website/blob/main/docs/administration/p2p-preheat/manage-preheat-providers.md (4)
https://github.com/goharbor/website/blob/main/docs/administration/robot-accounts/_index.md (4)

Do you want me to submit appropriate PRs?
