### ISSUE TITLE
Blog about cosign

### ISSUE THREAD

**Issue by a-mccarthy** [goharbor/website#312]
We should write up a blog that explains cosign in more depth. It should include an overview of cosign and how to signed a Harbor artifact with cosign.

**Comment by a-mccarthy** [comment]
@wy65701436 Orlin and I were thinking of writing a blog about using cosign with harbor. Do you have any ideas of a common use case or demo users would like to see? thanks!

**Comment by wy65701436** [comment]
@a-mccarthy , the main scenarios could be:

Manager Signature:

- create: Sign artifact with cosign and show linkage in harbor.
- delete: The signature can be removed ndividually or together with the subject artifact.
- copy: Copy artfact with signature from project A to B. User can see the artifact with signature in the project B.

Pull policy:

- User cannot pull any artifact without signature when the cosign policy is enabled.

Replication:

- Replicate any artifact with signature from Harbor A to Harbor B. Show it in Harbor B and do the `cosign verify` in Harbor B.

**Comment by OrlinVasilev** [comment]
@wy65701436 Maybe some automation parts like how easy would be get that working with Jenkins pipelines or something?

**Comment by wy65701436** [comment]
The flow could be:

User usurally have two harbor instances, one is staging(for pushing, build verification testing) and another is production(for pulling).

- CI pipeline builds & pushes one image into staging Harbor, and uses cosign to sign it.
- Staging Harbor triggers replcation the image the to production Harbor by event based. (It simulates that user passes their test on staging env and starts to replication to production env)
- Enable cosign pull policy and config webhook in production Harbor. Production send a request to the webhook server once the above replcation is success.
- Any client listens to the hook to start the verification by cosign verify and the depolyment by pulling image from production Harbor.

**Comment by OrlinVasilev** [comment]
@wy65701436 started working on it when I have something to review will ping you thanks!
