### ISSUE TITLE
Provide higher-resolution images for users and partners

### ISSUE THREAD

**Issue by lucperkins** [goharbor/website#36]
The current user and partner logos are very grainy. Better improved would provide a quick aesthetic win.

**Comment by jonasrosland** [comment]
I'll keep this issue open, but we have implemented higher-res images for most of the users and partners on the new website. I think it warrants a second pass though, before closing.

**Comment by a-mccarthy** [comment]
moved over to https://github.com/goharbor/harbor/issues/14685
