### ISSUE TITLE
Docs(bug): missing configure user settings cli page

### ISSUE THREAD

**Issue by OrlinVasilev** [goharbor/website#403]
![image](https://user-images.githubusercontent.com/7236111/212361562-66fb7e5c-0af7-46f7-8161-7611fa494c6e.png)
![image](https://user-images.githubusercontent.com/7236111/212361623-053491a5-cb85-4f5f-9adf-edcf5d8566f6.png)

https://goharbor.io/docs/2.7.0/install-config/configure-user-settings-cli.md

**Comment by PaarthAgarwal** [comment]
The `configure-user-settings-cli.md` has been renamed to `configure-system-settings-cli.md`
To fix the error, we need to update the link, but I think we should also change the text from "Configure Harbor User Settings at the command line" to "Configure Harbor System Settings at the command line".
Please let me know what you think, and I'll be more than happy to open a PR.
