### ISSUE TITLE
Upgrade docs for version 2.9, 2.10 and edge have incorrect minimum postgres version

### ISSUE THREAD

**Issue by anguswilliams** [goharbor/website#536]
Upgrade docs state minimum required postgres version is >= 10, but release notes for 2.9.0 state the minum required postgres version is >= 12.

> As of Harbor v2.9.0, only PostgreSQL >= 12 is supported for external databases. Before upgrading, you should make sure that your external databases are using a supported version of PostgreSQL.

https://github.com/goharbor/harbor/releases/tag/v2.9.0

**Comment by sergioarmgpl** [comment]
This is done, should be closed :) @anguswilliams

**Comment by anguswilliams** [comment]
Thanks @sergioarmgpl, closing :)
