### ISSUE TITLE
 Improve the existing Notation documentation

### ISSUE THREAD

**Issue by Roseline-Bassey** [goharbor/website#540]
Improve the existing [Notation documentation](https://goharbor.io/docs/2.9.0/working-with-projects/working-with-images/sign-images/#use-notationexperimental-to-sign-artifacts-with-distribution-spec-v11-mode) by demonstrating how to configure HTTPS domain for secure image signing and verification using the Notation CLI.

**Comment by Vad1mo** [comment]
This would be a good thing to improve.

**Comment by Roseline-Bassey** [comment]
Hi, @Vad1mo and thanks for your interest @OrlinVasilev 

I am currently working on this issue.

**Comment by OrlinVasilev** [comment]
Looking forward to see the updates!

great stuff thank you!
