### ISSUE TITLE
[Website] Text being cutoff 

### ISSUE THREAD

**Issue by amands98** [goharbor/website#542]
### Description

The text on the harbor website is being cut off.

Location - https://goharbor.io/docs/2.4.0/build-customize-contribute/registry-landscape/

Screenshots -> 

![image](https://github.com/goharbor/website/assets/136564604/4b6ad38c-866d-4f33-a487-e7297d663b32)

**Comment by sergioarmgpl** [comment]
Let me work on it @amands98

**Comment by sergioarmgpl** [comment]
I have a question, I have an option to set the table with custom styles, or maybe to configure the style that all the tables use by default what do you prefer? @OrlinVasilev

**Comment by OrlinVasilev** [comment]
I prefer a common way for all tables, so we minimize the risk of forgeting to customize in the future  :)
@sergioarmgpl I know we have discussed it , but can you open PR for that ?
Thank you!

**Comment by sergioarmgpl** [comment]
I will open the PR later today @OrlinVasilev

**Comment by sergioarmgpl** [comment]
This is the Issue @OrlinVasilev https://github.com/goharbor/website/pull/587

**Comment by sergioarmgpl** [comment]
This is how it looks 
![Screenshot 2024-10-30 at 10 37 57](https://github.com/user-attachments/assets/f765dd80-0b5c-4002-b4b0-de62d36bb952)

**Comment by sergioarmgpl** [comment]
The improvements for this PR is that the information is more readable with the scroll bar, here is the comparison
Before it looked like this:
 
![Screenshot 2024-11-05 at 15 33 51](https://github.com/user-attachments/assets/55c6c325-c72f-4824-be8b-c6132bd52269)

After adding a default CSS style that adds an horizontal scroll bar if necessary it will look like this:

At the Top
![Screenshot 2024-11-05 at 15 35 10](https://github.com/user-attachments/assets/2a8e01ea-e518-4843-a187-77b64a05efe4)

At the Bottom
![Screenshot 2024-11-05 at 15 34 37](https://github.com/user-attachments/assets/a0cb92b9-8752-4c98-922a-a6f2795ec660)

There are a lot of tables that have the same problem, so I added a CSS to all the tables, so all the tables will be fixed about this issue, a similar approach is currently used for CLI commands:
![Screenshot 2024-11-05 at 15 39 59](https://github.com/user-attachments/assets/459bf205-7185-4816-a265-c9f2b0095193)
