### ISSUE TITLE
Duplicate Logs Displayed Under the Project

### ISSUE THREAD

**Issue by Standing-Man** [goharbor/website#607]
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/8e53e695-994b-4756-8e1a-533a4e07316b" />

### current behavior:
The same log information is being shown multiple times, which could lead to confusion and inefficiency when reviewing the logs.

**Comment by Vad1mo** [comment]
@Standing-Man are you sure you are opening up this issue in the right project, I think you wanted to open it up in https://github.com/goharbor/harbor, also take a look in the existing issues and PRs, I think there is already a PR for that case.

**Comment by Standing-Man** [comment]
> @Standing-Man are you sure you are opening up this issue in the right project, I think you wanted to open it up in https://github.com/goharbor/harbor, also take a look in the existing issues and PRs, I think there is already a PR for that case.

Thank you for pointing that out! I’ll review the existing issues and PRs to confirm in that project if the case has already been addressed.  I’ll go ahead and close this for now. I appreciate your guidance!
