### ISSUE TITLE
The /docs/latest endpoint is broken

### ISSUE THREAD

**Issue by rosskusler** [goharbor/website#65]
Several links on the front page of the site are not working because /docs/latest/ is broken.

For instance the 'Harbor Installation and Configuration' link points to https://goharbor.io/docs/latest/install-config and the 'Harbor Administration' link points to https://goharbor.io/docs/latest/administration but neither of those links work.

Links to https://goharbor.io/docs/1.10/ work.. but not /docs/latest.

**Comment by rosskusler** [comment]
Looks like 65ced20ccf7ac7969211cf31db06189b541312a6  changed the structure of params.versions such that layouts/index.redirects needs to be changed sort of like this:

```
{{- $latest := index site.Params.versions 0 -}}
-/docs     /docs/{{ $latest }}
-/docs/latest     /docs/{{ $latest }}
-/docs/latest/*     /docs/{{ $latest }}/:splat
+/docs     /docs/{{ $latest.harborversion }}
+/docs/latest     /docs/{{ $latest.harborversion }}
+/docs/latest/*     /docs/{{ $latest.harborversion }}/:splat
```

**Comment by jonasrosland** [comment]
Hi @rosskusler , seems that you are correct!
Would you want to add this change into a PR?
